# Generated by Django 5.2.3 on 2025-07-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_downpayment_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ORDER_CREATED', 'Order Created'), ('DOWN_PAYMENT_UPLOADED', 'Down Payment Uploaded'), ('FULL_PAYMENT_UPLOADED', 'Full Payment Uploaded'), ('ORDER_APPROVED', 'Order Approved'), ('DOWN_PAYMENT_VERIFIED', 'Down Payment Verified'), ('FULL_PAYMENT_VERIFIED', 'Full Payment Verified'), ('ORDER_SHIPPED', 'Order Shipped')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
