# Generated by Django 5.2.3 on 2025-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('product', 'year', 'week_number')},
        ),
    ]
