# Generated by Django 5.2.3 on 2025-07-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_availability_year_alter_availability_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='expected_ship_date',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
