# Generated by Django 5.2.3 on 2025-07-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_availability_expected_ship_date_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
